using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CurrTracker
{
    class GuiElements
    {
        public static Dictionary<string, string> LoadCurrencyCombo()
        {
            Dictionary<string, string> currencyDictionary = new Dictionary<string, string>();

            currencyDictionary.Add("USDAED", "UNITED ARAB EMIRATES (THE) UAE Dirham");
            currencyDictionary.Add("USDAFN", "AFGHANISTAN Afghani");
            currencyDictionary.Add("USDALL", "ALBANIA Lek");
            currencyDictionary.Add("USDAMD", "ARMENIA Armenian Dram");
            currencyDictionary.Add("USDANG", "CURAÇAO Netherlands Antillean Guilder");
            currencyDictionary.Add("USDAOA", "ANGOLA Kwanza");
            currencyDictionary.Add("USDARS", "ARGENTINA Argentine Peso");
            currencyDictionary.Add("USDAUD", "AUSTRALIA Australian Dollar");
            currencyDictionary.Add("USDAWG", "ARUBA Aruban Florin");
            currencyDictionary.Add("USDAZN", "AZERBAIJAN Azerbaijan Manat");
            currencyDictionary.Add("USDBAM", "BOSNIA AND HERZEGOVINA Convertible Mark");
            currencyDictionary.Add("USDBBD", "BARBADOS Barbados Dollar");
            currencyDictionary.Add("USDBDT", "BANGLADESH Taka");
            currencyDictionary.Add("USDBGN", "BULGARIA Bulgarian Lev");
            currencyDictionary.Add("USDBHD", "BAHRAIN Bahraini Dinar");
            currencyDictionary.Add("USDBIF", "BURUNDI Burundi Franc");
            currencyDictionary.Add("USDBMD", "BERMUDA Bermudian Dollar");
            currencyDictionary.Add("USDBND", "BRUNEI DARUSSALAM Brunei Dollar");
            currencyDictionary.Add("USDBOB", "BOLIVIA (PLURINATIONAL STATE OF) Boliviano");
            currencyDictionary.Add("USDBRL", "BRAZIL Brazilian Real");
            currencyDictionary.Add("USDBSD", "BAHAMAS (THE) Bahamian Dollar");
            currencyDictionary.Add("USDBTC", "Bitcoin");
            currencyDictionary.Add("USDBTN", "BHUTAN Ngultrum");
            currencyDictionary.Add("USDBWP", "BOTSWANA Pula");
            currencyDictionary.Add("USDBYN", "BELARUS Belarusian (NEW) Ruble");
            currencyDictionary.Add("USDBYR", "BELARUS (OLD) Belarusian Ruble");
            currencyDictionary.Add("USDBZD", "BELIZE Belize Dollar");
            currencyDictionary.Add("USDCAD", "CANADA Canadian Dollar");
            currencyDictionary.Add("USDCDF", "CONGO (THE DEMOCRATIC REPUBLIC OF THE) Congolese Franc");
            currencyDictionary.Add("USDCHF", "LIECHTENSTEIN Swiss Franc");
            currencyDictionary.Add("USDCLF", "CHILE Unidad de Fomento");
            currencyDictionary.Add("USDCLP", "CHILE Chilean Peso");
            currencyDictionary.Add("USDCNY", "CHINA Yuan Renminbi");
            currencyDictionary.Add("USDCOP", "COLOMBIA Colombian Peso");
            currencyDictionary.Add("USDCRC", "COSTA RICA Costa Rican Colon");
            currencyDictionary.Add("USDCUC", "CUBA Peso Convertible");
            currencyDictionary.Add("USDCUP", "CUBA Cuban Peso");
            currencyDictionary.Add("USDCVE", "CABO VERDE Cabo Verde Escudo");
            currencyDictionary.Add("USDCZK", "CZECHIA Czech Koruna");
            currencyDictionary.Add("USDDJF", "DJIBOUTI Djibouti Franc");
            currencyDictionary.Add("USDDKK", "DENMARK Danish Krone");
            currencyDictionary.Add("USDDOP", "DOMINICAN REPUBLIC (THE) Dominican Peso");
            currencyDictionary.Add("USDDZD", "ALGERIA Algerian Dinar");
            currencyDictionary.Add("USDEGP", "EGYPT Egyptian Pound");
            currencyDictionary.Add("USDERN", "ERITREA Nakfa");
            currencyDictionary.Add("USDETB", "ETHIOPIA Ethiopian Birr");
            currencyDictionary.Add("USDEUR", "ÅLAND ISLANDS Euro");
            currencyDictionary.Add("USDFJD", "FIJI Fiji Dollar");
            currencyDictionary.Add("USDFKP", "FALKLAND ISLANDS (THE) [MALVINAS] Falkland Islands Pound");
            currencyDictionary.Add("USDGBP", "GUERNSEY Pound Sterling");
            currencyDictionary.Add("USDGEL", "GEORGIA Lari");
            currencyDictionary.Add("USDGGP", "GUERNSEY Pound ");
            currencyDictionary.Add("USDGHS", "GHANA Ghana Cedi");
            currencyDictionary.Add("USDGIP", "GIBRALTAR Gibraltar Pound");
            currencyDictionary.Add("USDGMD", "GAMBIA (THE) Dalasi");
            currencyDictionary.Add("USDGNF", "GUINEA Guinean Franc");
            currencyDictionary.Add("USDGTQ", "GUATEMALA Quetzal");
            currencyDictionary.Add("USDGYD", "GUYANA Guyana Dollar");
            currencyDictionary.Add("USDHKD", "HONG KONG Hong Kong Dollar");
            currencyDictionary.Add("USDHNL", "HONDURAS Lempira");
            currencyDictionary.Add("USDHRK", "CROATIA Kuna");
            currencyDictionary.Add("USDHTG", "HAITI Gourde");
            currencyDictionary.Add("USDHUF", "HUNGARY Forint");
            currencyDictionary.Add("USDIDR", "INDONESIA Rupiah");
            currencyDictionary.Add("USDILS", "ISRAEL New Israeli Sheqel");
            currencyDictionary.Add("USDIMP", "ISLE OF MAN Pound");
            currencyDictionary.Add("USDINR", "BHUTAN Indian Rupee");
            currencyDictionary.Add("USDIQD", "IRAQ Iraqi Dinar");
            currencyDictionary.Add("USDIRR", "IRAN (ISLAMIC REPUBLIC OF) Iranian Rial");
            currencyDictionary.Add("USDISK", "ICELAND Iceland Krona");
            currencyDictionary.Add("USDJMD", "JAMAICA Jamaican Dollar");
            currencyDictionary.Add("USDJOD", "JORDAN Jordanian Dinar");
            currencyDictionary.Add("USDJPY", "JAPAN Yen");
            currencyDictionary.Add("USDKES", "KENYA Kenyan Shilling");
            currencyDictionary.Add("USDKGS", "KYRGYZSTAN Som");
            currencyDictionary.Add("USDKHR", "CAMBODIA Riel");
            currencyDictionary.Add("USDKMF", "COMOROS (THE) Comorian Franc ");
            currencyDictionary.Add("USDKPW", "KOREA (THE DEMOCRATIC PEOPLE’S REPUBLIC OF) North Korean Won");
            currencyDictionary.Add("USDKRW", "KOREA (THE REPUBLIC OF) Won");
            currencyDictionary.Add("USDKWD", "KUWAIT Kuwaiti Dinar");
            currencyDictionary.Add("USDKYD", "CAYMAN ISLANDS (THE) Cayman Islands Dollar");
            currencyDictionary.Add("USDKZT", "KAZAKHSTAN Tenge");
            currencyDictionary.Add("USDLAK", "LAO PEOPLE’S DEMOCRATIC REPUBLIC (THE) Lao Kip");
            currencyDictionary.Add("USDLBP", "LEBANON Lebanese Pound");
            currencyDictionary.Add("USDLKR", "SRI LANKA Sri Lanka Rupee");
            currencyDictionary.Add("USDLRD", "LIBERIA Liberian Dollar");
            currencyDictionary.Add("USDLSL", "LESOTHO Loti");
            currencyDictionary.Add("USDLTL", "LITHUANIAN Litas");
            currencyDictionary.Add("USDLYD", "LIBYA Libyan Dinar");
            currencyDictionary.Add("USDMAD", "MOROCCO Moroccan Dirham");
            currencyDictionary.Add("USDMDL", "MOLDOVA (THE REPUBLIC OF) Moldovan Leu");
            currencyDictionary.Add("USDMGA", "MADAGASCAR Malagasy Ariary");
            currencyDictionary.Add("USDMKD", "MACEDONIA (THE FORMER YUGOSLAV REPUBLIC OF) Denar");
            currencyDictionary.Add("USDMMK", "MYANMAR Kyat");
            currencyDictionary.Add("USDMNT", "MONGOLIA Tugrik");
            currencyDictionary.Add("USDMOP", "MACAO Pataca");
            currencyDictionary.Add("USDMUR", "MAURITIUS Mauritius Rupee");
            currencyDictionary.Add("USDMVR", "MALDIVES Rufiyaa");
            currencyDictionary.Add("USDMWK", "MALAWI Malawi Kwacha");
            currencyDictionary.Add("USDMXN", "MEXICO Mexican Peso");
            currencyDictionary.Add("USDMYR", "MALAYSIA Malaysian Ringgit");
            currencyDictionary.Add("USDMZN", "MOZAMBIQUE Mozambique Metical");
            currencyDictionary.Add("USDNAD", "NAMIBIA Namibia Dollar");
            currencyDictionary.Add("USDNGN", "NIGERIA Naira");
            currencyDictionary.Add("USDNIO", "NICARAGUA Cordoba Oro");
            currencyDictionary.Add("USDNOK", "BOUVET ISLAND Norwegian Krone");
            currencyDictionary.Add("USDNPR", "NEPAL Nepalese Rupee");
            currencyDictionary.Add("USDNZD", "COOK ISLANDS (THE) New Zealand Dollar");
            currencyDictionary.Add("USDOMR", "OMAN Rial Omani");
            currencyDictionary.Add("USDPAB", "PANAMA Balboa");
            currencyDictionary.Add("USDPEN", "PERU Sol");
            currencyDictionary.Add("USDPGK", "PAPUA NEW GUINEA Kina");
            currencyDictionary.Add("USDPHP", "PHILIPPINES (THE) Philippine Peso");
            currencyDictionary.Add("USDPKR", "PAKISTAN Pakistan Rupee");
            currencyDictionary.Add("USDPLN", "POLAND Zloty");
            currencyDictionary.Add("USDPYG", "PARAGUAY Guarani");
            currencyDictionary.Add("USDQAR", "QATAR Qatari Rial");
            currencyDictionary.Add("USDRON", "ROMANIA Romanian Leu");
            currencyDictionary.Add("USDRSD", "SERBIA Serbian Dinar");
            currencyDictionary.Add("USDRUB", "RUSSIAN FEDERATION (THE) Russian Ruble");
            currencyDictionary.Add("USDRWF", "RWANDA Rwanda Franc");
            currencyDictionary.Add("USDSAR", "SAUDI ARABIA Saudi Riyal");
            currencyDictionary.Add("USDSBD", "SOLOMON ISLANDS Solomon Islands Dollar");
            currencyDictionary.Add("USDSCR", "SEYCHELLES Seychelles Rupee");
            currencyDictionary.Add("USDSDG", "SUDAN (THE) Sudanese Pound");
            currencyDictionary.Add("USDSEK", "SWEDEN Swedish Krona");
            currencyDictionary.Add("USDSGD", "SINGAPORE Singapore Dollar");
            currencyDictionary.Add("USDSHP", "SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA Saint Helena Pound");
            currencyDictionary.Add("USDSLL", "SIERRA LEONE Leone");
            currencyDictionary.Add("USDSOS", "SOMALIA Somali Shilling");
            currencyDictionary.Add("USDSRD", "SURINAME Surinam Dollar");
            currencyDictionary.Add("USDSVC", "EL SALVADOR El Salvador Colon");
            currencyDictionary.Add("USDSYP", "SYRIAN ARAB REPUBLIC Syrian Pound");
            currencyDictionary.Add("USDSZL", "ESWATINI Lilangeni");
            currencyDictionary.Add("USDTHB", "THAILAND Baht");
            currencyDictionary.Add("USDTJS", "TAJIKISTAN Somoni");
            currencyDictionary.Add("USDTMT", "TURKMENISTAN Turkmenistan New Manat");
            currencyDictionary.Add("USDTND", "TUNISIA Tunisian Dinar");
            currencyDictionary.Add("USDTOP", "TONGA Pa’anga");
            currencyDictionary.Add("USDTRY", "TURKEY Turkish Lira");
            currencyDictionary.Add("USDTTD", "TRINIDAD AND TOBAGO Trinidad and Tobago Dollar");
            currencyDictionary.Add("USDTWD", "TAIWAN (PROVINCE OF CHINA) New Taiwan Dollar");
            currencyDictionary.Add("USDTZS", "TANZANIA, UNITED REPUBLIC OF Tanzanian Shilling");
            currencyDictionary.Add("USDUAH", "UKRAINE Hryvnia");
            currencyDictionary.Add("USDUGX", "UGANDA Uganda Shilling");
            currencyDictionary.Add("USDUSD", "AMERICAN SAMOA US Dollar");
            currencyDictionary.Add("USDUYU", "URUGUAY Peso Uruguayo");
            currencyDictionary.Add("USDUZS", "UZBEKISTAN Uzbekistan Sum");
            currencyDictionary.Add("USDVND", "VIET NAM Dong");
            currencyDictionary.Add("USDVUV", "VANUATU Vatu");
            currencyDictionary.Add("USDWST", "SAMOA Tala");
            currencyDictionary.Add("USDXAF", "CAMEROON CFA Franc BEAC");
            currencyDictionary.Add("USDXAG", "ZZ11_Silver Silver");
            currencyDictionary.Add("USDXAU", "ZZ08_Gold Gold");
            currencyDictionary.Add("USDXCD", "ANGUILLA East Caribbean Dollar");
            currencyDictionary.Add("USDXDR", "INTERNATIONAL MONETARY FUND (IMF)  SDR (Special Drawing Right)");
            currencyDictionary.Add("USDXOF", "BENIN CFA Franc BCEAO");
            currencyDictionary.Add("USDXPF", "FRENCH POLYNESIA CFP Franc");
            currencyDictionary.Add("USDYER", "YEMEN Yemeni Rial");
            currencyDictionary.Add("USDZAR", "LESOTHO Rand");
            currencyDictionary.Add("USDZMW", "ZAMBIA Zambian Kwacha");
            currencyDictionary.Add("USDZWL", "ZIMBABWE Zimbabwe Dollar");

            return currencyDictionary;
        }
    }
}
